# Generated by Django 4.2 on 2025-02-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task',
            field=models.CharField(max_length=150),
        ),
    ]
