# Generated by Django 4.2 on 2025-02-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_alter_tasks_options_alter_users_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='priority',
            field=models.PositiveBigIntegerField(db_index=True, default=1),
        ),
    ]
