# Generated by Django 4.2 on 2025-02-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0003_alter_tasks_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='priority',
            field=models.PositiveSmallIntegerField(db_index=True, default=1),
        ),
    ]
